name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy application
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}  # or SERVER_IP if using IP
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DOMAIN << 'EOF'
          cd $SERVER_PATH
          git pull origin main
          composer install --prefer-dist --no-dev --no-scripts --no-progress --no-suggest
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link
          sudo systemctl restart php-fpm
          sudo systemctl restart nginx
        EOF
