name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4.33'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Show .env file
      run: cat .env

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Show Database Directory
      run: ls -la database

    - name: Import SQL File into SQLite
      run: sqlite3 database/database.sqlite < database/database.sql

    - name: Migrate Database Tables
      run: php artisan migrate --force

    - name: Migrate Specific Migrations
      run: |
        php artisan migrate --force --path=/database/migrations/2022_10_16_071643_create_pasiens_table.php
        php artisan migrate --force --path=/database/migrations/2022_10_15_054340_create_values_table.php
        php artisan migrate --force --path=/database/migrations/2022_08_15_074729_create_sensors_table.php

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
