name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: composer install --no-dev --prefer-dist --no-scripts --no-progress

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --testdox

  deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Dependencies and Build
      run: |
        composer install --no-dev --prefer-dist --no-scripts --no-progress
        npm install --no-optional --no-audit --no-fund --silent --progress=false
        npm run production

    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_DOMAIN }} "cd ${{ secrets.SERVER_PATH }} && \
          git pull origin main && \
          composer install --no-dev --prefer-dist --no-scripts --no-progress && \
          php artisan migrate --force && \
          php artisan config:cache && \
          php artisan route:cache && \
          php artisan view:cache && \
          php artisan storage:link && \
          sudo systemctl restart php-fpm && \
          sudo systemctl restart nginx"

